language: go

go_import_path: github.com/FlorentinDUBOIS/bouncer

go:
  - master
  - 1.8
  - 1.7
  - 1.6

install:
  - make install

before_script:
  - pwd
  - ls
  - ls vendor
  - make format

script:
  - make lint
  - make
