language: go

go:
  - 1.8
  - 1.7
  - 1.6

go_import_path: github.com/FlorentinDUBOIS/bouncer

before_script:
  - make get
  - make lint-install

script:
  - make glide-install
  - make lint
  - make format
  - make
